<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\src\ResourceKit\ResourceKit.csproj" />
	</ItemGroup>
</Project>
