// <auto-generated />

#nullable enable

namespace Purview.Aspire.ResourceIsolation;

{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class HostResourceAttribute : global::System.Attribute;
