// <auto-generated />

#nullable enable

namespace Purview.Aspire.ResourceKit;

{{CodeGen}}
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class ResourceDefinitionAttribute : global::System.Attribute
{
	public ResourceDefinitionAttribute()
	{
	}

	public ResourceDefinitionAttribute(string name, string propertyName, bool generateOptions = true)
	{
		Name = name;
		PropertyName = propertyName;
		GenerateOptions = generateOptions;
	}

	public ResourceDefinitionAttribute(string name, bool generateOptions = true)
	{
		Name = name;
		GenerateOptions = generateOptions;
	}

	public string? Name { get; set; }

	public string? PropertyName { get; set; }

	public bool GenerateOptions { get; set; } = true;
}
