using Purview.Aspire.ResourceKit.SourceGeneration.Models;

namespace Purview.Aspire.ResourceKit.SourceGeneration;

partial class HostKitGenerator
{
	static CodeWriter BuildSource(HostKitGenerationModel hostKitInfo, CancellationToken cancellationToken)
	{
		var writer = new CodeWriter(
			$"{AssemblyInfo.AssemblyName}.{nameof(HostKitGenerator)}",
			AssemblyInfo.Version,
			throwOnUnclosedScopes: true
		);
		
		writer
			.WriteAutoGeneratedHeader(pragmas: ["CS8601", "CS8618"])
			.WriteUsing("global::Microsoft.Extensions.Configuration")
			.WriteUsing("global::Microsoft.Extensions.DependencyInjection")
			.WriteUsing("global::Microsoft.Extensions.Options")
			.WriteUsing("global::System")
			.NewLine();

		cancellationToken.ThrowIfCancellationRequested();

		BuildHostKit(hostKitInfo, context, null, cancellationToken);
		BuildResourceKitBase(hostKitInfo, context, null, cancellationToken);
		BuildResourceKits(hostKitInfo, context, null, cancellationToken);
		BuildExtensionClass(hostKitInfo, context, null, cancellationToken);

		return writer;
	}
}
