using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Purview.Aspire.ResourceIsolation.SourceGeneration.Helpers;
using Purview.Aspire.ResourceIsolation.SourceGeneration.Models;
using Purview.Aspire.ResourceIsolation.SourceGeneration.Templates;

namespace Purview.Aspire.ResourceIsolation.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed partial class HostAppGenerator : IIncrementalGenerator, ILogSupport
{
	GenerationLogger? _logger;

	const string HostResourceInterfaceName = "IHostAppResource";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static postInitContext =>
		{
			postInitContext.AddEmbeddedAttributeDefinition();

			foreach (var resourceName in TypeHelpers.GeneratedTypes)
				postInitContext.AddSource(resourceName, EmbeddedResources.LoadTemplate(resourceName));
		});

		// Collect all of the host app types.
		var valueProviders = SourceGenHelpers.GetGeneratorValueProviders(context, _logger);

		context.RegisterSourceOutput(
			valueProviders,
			static (sourceProductionContext, model) =>
			{
				if (!model.IsSourceGeneratorEnabled)
					return;

				List<DiagnosticInfo> diagnostics = [];
				if (model.HostApp.HasDiagnostics)
					diagnostics.AddRange(model.HostApp.Diagnostics);
				if (!model.Diagnostics.IsDefaultOrEmpty)
					diagnostics.AddRange(model.Diagnostics);

				if (model.HostResources.IsDefaultOrEmpty)
				{
					if (model.HostApp.IsEmpty)
						diagnostics.Add(GeneratorDiagnostics.Create(GeneratorDiagnostics.NoHostResourcesDefined));
				}
				else if (model.HostApp.IsEmpty)
					diagnostics.Add(GeneratorDiagnostics.Create(GeneratorDiagnostics.NoHostAppInfoDefined));

				// Report any diagnostics that were collected during the generation process.
				if (diagnostics.Count > 0)
					ReportDiagnostics(sourceProductionContext, diagnostics, model.GenerationContext.Logger);

				// If any fatal diagnostics were reported, do not generate any source code.
				if (model.HostApp.IsFatal || model.HostResources.Any(s => s.IsFatal))
					return;

				foreach (var m in model)
				{
					var source = BuildHostAppSource(model);
					sourceProductionContext.AddSource(
						$"{SanitizeForFileName(model.HostAppType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))}.HostResources.g.cs",
						SourceText.From(source, Encoding.UTF8)
					);
				}
			}
		);
	}

	static string BuildHostAppSource(GeneratedHostAppModel model)
	{
		var hostAppType = model.HostAppType;
		var hostNamespace = hostAppType.ContainingNamespace.IsGlobalNamespace
			? null
			: hostAppType.ContainingNamespace.ToDisplayString();
		var hostAppTypeDisplay = hostAppType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		var hostAppTypeName = hostAppType.Name;
		var hostAccessibility = GetAccessibilityKeyword(hostAppType.DeclaredAccessibility);

		var resources = model.Resources;
		var variableMap = CreateUniqueVariableMap(resources);
		var buildResourceLines = resources
			.Select(r =>
			{
				var resourceType = r.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				return $"\t\tvar {variableMap[r]} = serviceProvider.GetRequiredService<{resourceType}>();";
			})
			.ToArray();

		var buildInvokeLines = resources.Select(r => $"\t\t{variableMap[r]}.BuildResource(builder);").ToArray();

		var configureInvokeLines = resources.Select(r => $"\t\t{variableMap[r]}.ConfigureResource(this);").ToArray();

		var registrationLines = resources
			.Select(static r =>
			{
				var resourceType = r.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
				return $"\t\tbuilder.Services.TryAddSingleton<{resourceType}>();";
			})
			.ToArray();

		var builder = new StringBuilder();
		builder.AppendLine("// <auto-generated />");
		builder.AppendLine("#nullable enable");
		builder.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
		builder.AppendLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
		builder.AppendLine();

		if (hostNamespace is not null)
		{
			builder.Append("namespace ").Append(hostNamespace).AppendLine(";");
			builder.AppendLine();
		}

		if (!string.IsNullOrEmpty(hostAccessibility))
			builder.Append(hostAccessibility).Append(' ');

		builder.Append("partial class ").Append(hostAppTypeName).AppendLine();
		builder.AppendLine("{");
		builder.AppendLine(
			"\tpublic void Initialize(global::Aspire.Hosting.IDistributedApplicationBuilder builder, global::System.IServiceProvider serviceProvider)"
		);
		builder.AppendLine("\t{");
		builder.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(builder);");
		builder.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
		builder.AppendLine();
		builder.AppendLine("\t\tBuild(builder, serviceProvider);");
		builder.AppendLine("\t\tConfigure(serviceProvider);");
		builder.AppendLine("\t}");
		builder.AppendLine();
		builder.AppendLine(
			"\tpublic void Build(global::Aspire.Hosting.IDistributedApplicationBuilder builder, global::System.IServiceProvider serviceProvider)"
		);
		builder.AppendLine("\t{");
		builder.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(builder);");
		builder.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
		builder.AppendLine();

		if (buildResourceLines.Length == 0)
			builder.AppendLine("\t\t// No host resources were discovered for this host app.");
		else
		{
			foreach (var line in buildResourceLines)
				builder.AppendLine(line);
			builder.AppendLine();
			foreach (var line in buildInvokeLines)
				builder.AppendLine(line);
		}

		builder.AppendLine("\t}");
		builder.AppendLine();
		builder.AppendLine("\tpublic void Configure(global::System.IServiceProvider serviceProvider)");
		builder.AppendLine("\t{");
		builder.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
		builder.AppendLine();

		if (buildResourceLines.Length == 0)
			builder.AppendLine("\t\t// No host resources were discovered for this host app.");
		else
		{
			foreach (var line in buildResourceLines)
				builder.AppendLine(line);
			builder.AppendLine();
			foreach (var line in configureInvokeLines)
				builder.AppendLine(line);
		}

		builder.AppendLine("\t}");
		builder.AppendLine("}");
		builder.AppendLine();

		builder.Append("internal static class ").Append(hostAppTypeName).AppendLine("BuilderExtensions");
		builder.AppendLine("{");
		builder.AppendLine(
			"\tpublic static global::Aspire.Hosting.IDistributedApplicationBuilder AddHostAppResources(this global::Aspire.Hosting.IDistributedApplicationBuilder builder, global::System.Action<global::Microsoft.Extensions.DependencyInjection.IServiceCollection>? configureServices = null)"
		);
		builder.AppendLine("\t{");
		builder.AppendLine("\t\tglobal::System.ArgumentNullException.ThrowIfNull(builder);");
		builder.AppendLine();
		builder.AppendLine("\t\tconfigureServices?.Invoke(builder.Services);");
		builder.AppendLine();
		builder.Append("\t\tbuilder.Services.TryAddSingleton<").Append(hostAppTypeDisplay).AppendLine(">();");

		if (registrationLines.Length > 0)
		{
			foreach (var line in registrationLines)
				builder.AppendLine(line);
		}

		builder.AppendLine();
		builder.AppendLine("\t\tusing var serviceProvider = builder.Services.BuildServiceProvider();");
		builder
			.Append(
				"\t\tvar hostApp = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance<"
			)
			.Append(hostAppTypeDisplay)
			.AppendLine(">(serviceProvider);");
		builder.AppendLine("\t\thostApp.Initialize(builder, serviceProvider);");
		builder.AppendLine();
		builder.AppendLine("\t\treturn builder;");
		builder.AppendLine("\t}");
		builder.AppendLine("}");

		return builder.ToString();
	}

	static string GetAccessibilityKeyword(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Internal => "internal",
			Accessibility.Private => "private",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedAndInternal => "private protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			_ => string.Empty,
		};
	}

	static Dictionary<INamedTypeSymbol, string> CreateUniqueVariableMap(ImmutableArray<INamedTypeSymbol> resources)
	{
		var map = new Dictionary<INamedTypeSymbol, string>(NamedTypeSymbolComparer.Instance);
		var seen = new Dictionary<string, int>(StringComparer.Ordinal);

		foreach (var resource in resources)
		{
			var baseName = BuildVariableName(resource.Name);
			if (seen.TryGetValue(baseName, out var count))
			{
				count++;
				seen[baseName] = count;
				map[resource] = $"{baseName}{count}";
			}
			else
			{
				seen[baseName] = 0;
				map[resource] = baseName;
			}
		}

		return map;
	}

	sealed class NamedTypeSymbolComparer : IEqualityComparer<INamedTypeSymbol>
	{
		public static NamedTypeSymbolComparer Instance { get; } = new();

		public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y) => SymbolEqualityComparer.Default.Equals(x, y);

		public int GetHashCode(INamedTypeSymbol obj) => SymbolEqualityComparer.Default.GetHashCode(obj);
	}

	static string BuildVariableName(string typeName)
	{
		var trimmed = typeName.EndsWith("AppResource", StringComparison.Ordinal)
			? typeName.Substring(0, typeName.Length - "AppResource".Length)
			: typeName;

		if (string.IsNullOrWhiteSpace(trimmed))
			trimmed = "resource";

		if (trimmed.Length == 1)
			return char.ToLowerInvariant(trimmed[0]).ToString();

		return char.ToLowerInvariant(trimmed[0]) + trimmed.Substring(1);
	}

	static bool IsHostAppCandidate(INamedTypeSymbol typeSymbol)
	{
		if (typeSymbol.TypeKind != TypeKind.Class || typeSymbol.IsAbstract)
			return false;

		return typeSymbol
			.GetAttributes()
			.Any(attribute =>
				string.Equals(attribute.AttributeClass?.Name, HostResourcesAttributeName, StringComparison.Ordinal)
				|| string.Equals(attribute.AttributeClass?.Name, "HostResources", StringComparison.Ordinal)
			);
	}

	static bool IsResourceForHostApp(INamedTypeSymbol resourceType, INamedTypeSymbol hostAppType)
	{
		if (resourceType.TypeKind != TypeKind.Class || resourceType.IsAbstract)
			return false;

		foreach (var @interface in resourceType.AllInterfaces)
		{
			if (!string.Equals(@interface.Name, HostResourceInterfaceName, StringComparison.Ordinal))
				continue;

			if (
				!string.Equals(
					@interface.ContainingNamespace.ToDisplayString(),
					ResourceIsolationNamespace,
					StringComparison.Ordinal
				)
			)
				continue;

			if (@interface.TypeArguments.Length != 1)
				continue;

			if (SymbolEqualityComparer.Default.Equals(@interface.TypeArguments[0], hostAppType))
				return true;
		}

		return false;
	}

	static IEnumerable<INamedTypeSymbol> GetAllNamedTypes(INamespaceSymbol namespaceSymbol)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol nestedNamespace)
			{
				foreach (var nestedType in GetAllNamedTypes(nestedNamespace))
					yield return nestedType;
			}
		}

		foreach (var type in namespaceSymbol.GetTypeMembers())
		{
			yield return type;

			foreach (var nestedType in GetNestedTypes(type))
				yield return nestedType;
		}
	}

	static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol typeSymbol)
	{
		foreach (var nestedType in typeSymbol.GetTypeMembers())
		{
			yield return nestedType;

			foreach (var childType in GetNestedTypes(nestedType))
				yield return childType;
		}
	}

	static string SanitizeForFileName(string value)
	{
		var invalid = Path.GetInvalidFileNameChars();
		var builder = new StringBuilder(value.Length);

		foreach (var ch in value)
			builder.Append(invalid.Contains(ch) ? '_' : ch);

		return builder.ToString();
	}

	readonly struct GeneratedHostAppModel(INamedTypeSymbol hostAppType, ImmutableArray<INamedTypeSymbol> resources)
	{
		public INamedTypeSymbol HostAppType { get; } = hostAppType;

		public ImmutableArray<INamedTypeSymbol> Resources { get; } = resources;
	}
}
