using Purview.Aspire.ResourceKit.SourceGeneration.Helpers;
using Purview.Aspire.ResourceKit.SourceGeneration.Models;

namespace Purview.Aspire.ResourceKit.SourceGeneration;

partial class HostKitGenerator
{
	static string BuildSource(
		HostKitInfo hostKitInfo,
		KitGenerationContext context,
		GenerationLogger? logger,
		CancellationToken cancellationToken
	)
	{
		var writer = context.CreateCodeWriter();

		writer
			.WriteAutoGeneratedHeader(pragmas: ["CS8601", "CS8618"])
			.WriteUsing("global::Microsoft.Extensions.Configuration")
			.WriteUsing("global::Microsoft.Extensions.DependencyInjection")
			.WriteUsing("global::Microsoft.Extensions.Options")
			.WriteUsing("global::System")
			.NewLine();

		cancellationToken.ThrowIfCancellationRequested();

		BuildHostKit(hostKitInfo, context, logger, cancellationToken);
		BuildResourceKitBase(hostKitInfo, context, logger, cancellationToken);
		BuildResourceKits(hostKitInfo, context, logger, cancellationToken);
		BuildExtensionClass(hostKitInfo, context, logger, cancellationToken);

		return SourceGenLibrary.AddCodeGen(writer.ToString());
	}
}
