using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Purview.Aspire.ResourceIsolation.SourceGeneration.Helpers;
using Purview.Aspire.ResourceIsolation.SourceGeneration.Models;
using Purview.Aspire.ResourceIsolation.SourceGeneration.Templates;

namespace Purview.Aspire.ResourceIsolation.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed partial class HostAppGenerator : IIncrementalGenerator, ILogSupport
{
	GenerationLogger? _logger;

	static readonly SymbolDisplayFormat FullyQualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static postInitContext =>
		{
			postInitContext.AddEmbeddedAttributeDefinition();

			foreach (var resourceName in TypeHelpers.GeneratedTypes)
				postInitContext.AddSource(resourceName, EmbeddedResources.LoadTemplate(resourceName));
		});

		// Collect all of the host app types and host resource types.
		var valueProviders = SourceGenHelpers.GetGeneratorValueProviders(context, _logger);

		context.RegisterSourceOutput(
			valueProviders,
			static (sourceProductionContext, model) =>
			{
				if (!model.IsSourceGeneratorEnabled)
					return;

				List<DiagnosticInfo> diagnostics = [];
				if (model.HostApp.HasDiagnostics)
					diagnostics.AddRange(model.HostApp.Diagnostics);
				if (!model.Diagnostics.IsDefaultOrEmpty)
					diagnostics.AddRange(model.Diagnostics);

				// Collect any diagnostics from the host resource results.
				foreach (var resourceResult in model.HostResources)
				{
					if (resourceResult.HasDiagnostics)
						diagnostics.AddRange(resourceResult.Diagnostics);
				}

				// Resolve the host app symbol (if any).
				var hostAppSymbol = model.HostApp.IsSuccess ? model.HostApp.Value!.Symbol : null;

				// Resolve the host resource symbols, filtering to those that target this host app.
				ImmutableArray<INamedTypeSymbol> resourceSymbols;
				if (hostAppSymbol is not null)
				{
					var resources = new List<INamedTypeSymbol>();
					foreach (var resourceResult in model.HostResources)
					{
						if (!resourceResult.IsSuccess)
							continue;

						var resourceSymbol = resourceResult.Value!.Symbol;
						if (IsResourceForHostApp(resourceSymbol, hostAppSymbol))
							resources.Add(resourceSymbol);
					}

					resourceSymbols = [.. resources.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>()];
				}
				else
				{
					resourceSymbols = [];
				}

				if (resourceSymbols.IsDefaultOrEmpty)
				{
					if (model.HostApp.IsEmpty)
						diagnostics.Add(
							GeneratorDiagnostics.Create(GeneratorDiagnostics.NoHostResourcesDefined, hostAppSymbol)
						);
				}
				else if (model.HostApp.IsEmpty)
					diagnostics.Add(GeneratorDiagnostics.Create(GeneratorDiagnostics.NoHostAppInfoDefined));

				// Report any diagnostics that were collected during the generation process.
				if (diagnostics.Count > 0)
					ReportDiagnostics(sourceProductionContext, diagnostics, model.GenerationContext.Logger);

				// If any fatal diagnostics were reported, do not generate any source code.
				if (model.HostApp.IsFatal || model.HostResources.Any(s => s.IsFatal))
					return;

				// We only support a single host app - if none was found, there is nothing to generate.
				if (hostAppSymbol is null)
					return;

				var generatedModel = new GeneratedHostAppModel(hostAppSymbol, resourceSymbols);
				var source = BuildHostAppSource(generatedModel);
				var fileName =
					$"{SanitizeForFileName(hostAppSymbol.ToDisplayString(FullyQualifiedFormat))}.HostResources.g.cs";
				sourceProductionContext.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
			}
		);
	}

	static string BuildHostAppSource(GeneratedHostAppModel model)
	{
		var hostAppType = model.HostAppType;
		var hostNamespace = hostAppType.ContainingNamespace.IsGlobalNamespace
			? null
			: hostAppType.ContainingNamespace.ToDisplayString();
		var hostAppTypeDisplay = hostAppType.ToDisplayString(FullyQualifiedFormat);
		var hostAppTypeName = hostAppType.Name;
		var hostAccessibility = GetAccessibilityKeyword(hostAppType.DeclaredAccessibility);

		var resources = model.Resources;
		var variableMap = CreateUniqueVariableMap(resources);
		var propertyNameMap = CreatePropertyNameMap(resources);

		var writer = new CodeWriter();

		// The CodeWriter.Begin() scope resets the writer on dispose, so capture
		// the string before leaving the using block.
		string source;
		using (writer.Begin())
		{
			writer.WriteLine("// <auto-generated />");
			writer.WriteLine("#nullable enable");
			writer.WriteLine("using global::Microsoft.Extensions.DependencyInjection;");
			writer.WriteLine("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
			writer.WriteLine("using global::System;");
			writer.WriteLine("using global::System.Linq;");
			writer.NewLine();

			if (hostNamespace is not null)
			{
				writer.WriteLine($"namespace {hostNamespace};");
				writer.NewLine();
			}

			// --- Host app partial class ---
			if (!string.IsNullOrEmpty(hostAccessibility))
				writer.Write($"{hostAccessibility} ");

			writer.WriteLine($"partial class {hostAppTypeName}");

			using (writer.Block())
			{
				// Public properties for each host resource.
				if (resources.Length == 0)
				{
					writer.WriteLine("// No host resources were discovered for this host app.");
					writer.NewLine();
				}
				else
				{
					foreach (var resource in resources)
					{
						var resourceType = resource.ToDisplayString(FullyQualifiedFormat);
						var propertyName = propertyNameMap[resource];
						writer.Write($"public {resourceType} {propertyName} ");
						writer.WriteLine("{ get; private set; } = default!;");
					}
					writer.NewLine();
				}

				// Initialize method.
				writer.WriteLine(
					"public void Initialize(global::Aspire.Hosting.IDistributedApplicationBuilder builder, global::System.IServiceProvider serviceProvider)"
				);
				using (writer.Block())
				{
					writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(builder);");
					writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
					writer.NewLine();
					writer.WriteLine("Build(builder, serviceProvider);");
					writer.WriteLine("Configure(serviceProvider);");
				}
				writer.NewLine();

				// Build method.
				writer.WriteLine(
					"void Build(global::Aspire.Hosting.IDistributedApplicationBuilder builder, global::System.IServiceProvider serviceProvider)"
				);
				using (writer.Block())
				{
					writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(builder);");
					writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
					writer.NewLine();

					if (resources.Length == 0)
						writer.WriteLine("// No host resources were discovered for this host app.");
					else
					{
						foreach (var resource in resources)
						{
							var resourceType = resource.ToDisplayString(FullyQualifiedFormat);
							var variableName = variableMap[resource];
							var propertyName = propertyNameMap[resource];
							writer.WriteLine($"var {variableName} = serviceProvider.GetRequiredService<{resourceType}>();");
							writer.WriteLine($"{variableName}.BuildResource(builder);");
							writer.WriteLine($"{propertyName} = {variableName};");
						}
					}
				}
				writer.NewLine();

				// Configure method.
				writer.WriteLine("void Configure(global::System.IServiceProvider serviceProvider)");
				using (writer.Block())
				{
					writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(serviceProvider);");
					writer.NewLine();

					if (resources.Length == 0)
						writer.WriteLine("// No host resources were discovered for this host app.");
					else
					{
						foreach (var resource in resources)
						{
							var propertyName = propertyNameMap[resource];
							writer.WriteLine($"{propertyName}.ConfigureResource(this);");
						}
					}
				}
			}
			writer.NewLine();

			// --- Builder extensions ---
			writer.WriteLine($"internal static class {hostAppTypeName}BuilderExtensions");
			using (writer.Block())
			{
				writer.WriteLine(
					"public static global::Aspire.Hosting.IDistributedApplicationBuilder AddHostAppResources(this global::Aspire.Hosting.IDistributedApplicationBuilder builder, global::System.Action<global::Microsoft.Extensions.DependencyInjection.IServiceCollection>? configureServices = null)"
				);
				using (writer.Block())
				{
					writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(builder);");
					writer.NewLine();
					writer.WriteLine("configureServices?.Invoke(builder.Services);");
					writer.NewLine();
					writer.WriteLine($"builder.Services.TryAddSingleton<{hostAppTypeDisplay}>();");

					if (resources.Length > 0)
					{
						foreach (var resource in resources)
						{
							var resourceType = resource.ToDisplayString(FullyQualifiedFormat);
							writer.WriteLine($"builder.Services.TryAddSingleton<{resourceType}>();");
						}
					}

					writer.NewLine();
					writer.WriteLine("using var serviceProvider = builder.Services.BuildServiceProvider();");
					writer.WriteLine(
						$"var hostApp = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance<{hostAppTypeDisplay}>(serviceProvider);"
					);
					writer.WriteLine("hostApp.Initialize(builder, serviceProvider);");
					writer.NewLine();
					writer.WriteLine("return builder;");
				}
			}

			source = writer.ToString();
		}

		return source;
	}

	static string GetAccessibilityKeyword(Accessibility accessibility)
	{
		return accessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Internal => "internal",
			Accessibility.Private => "private",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedAndInternal => "private protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			_ => string.Empty,
		};
	}

	static Dictionary<INamedTypeSymbol, string> CreateUniqueVariableMap(ImmutableArray<INamedTypeSymbol> resources)
	{
		var map = new Dictionary<INamedTypeSymbol, string>(NamedTypeSymbolComparer.Instance);
		var seen = new Dictionary<string, int>(StringComparer.Ordinal);

		foreach (var resource in resources)
		{
			var baseName = BuildVariableName(resource.Name);
			if (seen.TryGetValue(baseName, out var count))
			{
				count++;
				seen[baseName] = count;
				map[resource] = $"{baseName}{count}";
			}
			else
			{
				seen[baseName] = 0;
				map[resource] = baseName;
			}
		}

		return map;
	}

	static Dictionary<INamedTypeSymbol, string> CreatePropertyNameMap(ImmutableArray<INamedTypeSymbol> resources)
	{
		// Property names are PascalCase derived from the resource type name,
		// with deduplication by appending a numeric suffix.
		var map = new Dictionary<INamedTypeSymbol, string>(NamedTypeSymbolComparer.Instance);
		var seen = new Dictionary<string, int>(StringComparer.Ordinal);

		foreach (var resource in resources)
		{
			var baseName = BuildPropertyName(resource.Name);
			if (seen.TryGetValue(baseName, out var count))
			{
				count++;
				seen[baseName] = count;
				map[resource] = $"{baseName}{count}";
			}
			else
			{
				seen[baseName] = 0;
				map[resource] = baseName;
			}
		}

		return map;
	}

	sealed class NamedTypeSymbolComparer : IEqualityComparer<INamedTypeSymbol>
	{
		public static NamedTypeSymbolComparer Instance { get; } = new();

		public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y) => SymbolEqualityComparer.Default.Equals(x, y);

		public int GetHashCode(INamedTypeSymbol obj) => SymbolEqualityComparer.Default.GetHashCode(obj);
	}

	static string BuildVariableName(string typeName)
	{
		var trimmed = TrimSuffix(typeName);
		if (string.IsNullOrWhiteSpace(trimmed))
			trimmed = "resource";

		return ToCamelCase(trimmed);
	}

	static string BuildPropertyName(string typeName)
	{
		var trimmed = TrimSuffix(typeName);
		if (string.IsNullOrWhiteSpace(trimmed))
			trimmed = "Resource";

		return ToPascalCase(trimmed);
	}

	static string TrimSuffix(string typeName) =>
		typeName.EndsWith("AppResource", StringComparison.Ordinal)
			? typeName.Substring(0, typeName.Length - "AppResource".Length)
		: typeName.EndsWith("Resource", StringComparison.Ordinal)
			? typeName.Substring(0, typeName.Length - "Resource".Length)
		: typeName;

	static string ToCamelCase(string value)
	{
		if (string.IsNullOrEmpty(value))
			return value;

		return value.Length == 1
			? char.ToLowerInvariant(value[0]).ToString()
			: char.ToLowerInvariant(value[0]) + value.Substring(1);
	}

	static string ToPascalCase(string value)
	{
		if (string.IsNullOrEmpty(value))
			return value;

		return value.Length == 1
			? char.ToUpperInvariant(value[0]).ToString()
			: char.ToUpperInvariant(value[0]) + value.Substring(1);
	}

	/// <summary>
	/// Determines whether the given resource type implements <see cref="IHostAppResource{T}"/>
	/// for the specified host app type.
	/// </summary>
	static bool IsResourceForHostApp(INamedTypeSymbol resourceType, INamedTypeSymbol hostAppType)
	{
		if (resourceType.TypeKind != TypeKind.Class || resourceType.IsAbstract)
			return false;

		foreach (var @interface in resourceType.AllInterfaces)
		{
			if (!string.Equals(@interface.Name, TypeHelpers.HostResourceInterfaceName, StringComparison.Ordinal))
				continue;

			if (
				!string.Equals(
					@interface.ContainingNamespace.ToDisplayString(),
					TypeHelpers.ResourceIsolationNamespace,
					StringComparison.Ordinal
				)
			)
				continue;

			if (@interface.TypeArguments.Length != 1)
				continue;

			if (SymbolEqualityComparer.Default.Equals(@interface.TypeArguments[0], hostAppType))
				return true;
		}

		return false;
	}

	static string SanitizeForFileName(string typeName)
	{
		var sb = new StringBuilder(typeName.Length);
		foreach (var c in typeName)
		{
			if (c is '_' or '.' or ':' or '<' or '>' or ',' or ' ' or '`' or '{' or '}')
				sb.Append('_');
			else
				sb.Append(c);
		}

		return sb.ToString();
	}
}
