using Microsoft.CodeAnalysis.Text;
using Purview.Aspire.ResourceKit.SourceGeneration.Models;

namespace Purview.Aspire.ResourceKit.SourceGeneration.Helpers;

static partial class CodeGenEmiiter
{
	public static IEnumerable<(string HintName, SourceText Source)> EmitAttributes()
	{
		yield return ($"{nameof(HostKitAttribute)}.g.cs", HostKitAttribute());
		yield return ("ResourceDefinitionAttribute.g.cs", ResourceKitDefinitionAttribute());
	}

	public static CodeWriter Emit(OutputContext outputContext, CancellationToken cancellationToken)
	{
		var writer = outputContext.Writer;
		writer
			.AutoGeneratedHeader(pragmas: ["CS8601", "CS8618"])
			.Using(TypeLibrary.Microsoft.Extensions.Configuration.Namespace)
			.Using(TypeLibrary.Microsoft.Extensions.DependencyInjection.Namespace)
			.Using(TypeLibrary.Microsoft.Extensions.Options.Namespace)
			.Using(TypeLibrary.System.Namespace);

		cancellationToken.ThrowIfCancellationRequested();

		EmitHostKit(outputContext, cancellationToken);
		EmitResourceKitBase(outputContext, cancellationToken);
		EmitResourceKits(outputContext, cancellationToken);
		EmitExtensionClass(outputContext, cancellationToken);

		return writer;
	}
}
