using Purview.Aspire.ResourceKit.SourceGeneration.Models;

namespace Purview.Aspire.ResourceKit.SourceGeneration.Helpers;

static partial class CodeGenEmiiter
{
	public static CodeWriter Emit(OutputContext outputContext, CancellationToken cancellationToken)
	{
		var writer = outputContext.Writer;
		writer
			.WriteAutoGeneratedHeader(pragmas: ["CS8601", "CS8618"])
			.WriteUsing(TypeLibrary.ConfigurationBinder.Namespace!)
			.WriteUsing(TypeLibrary.IServiceCollection.Namespace!)
			.WriteUsing(TypeLibrary.OptionsBuilder.Namespace!)
			.WriteUsing(TypeLibrary.Action.Namespace!);

		cancellationToken.ThrowIfCancellationRequested();

		EmitHostKit(outputContext, cancellationToken);
		EmitResourceKitBase(outputContext, cancellationToken);
		EmitResourceKits(outputContext, cancellationToken);
		EmitExtensionClass(outputContext, cancellationToken);

		return writer;
	}
}
