using Microsoft.CodeAnalysis;

namespace Purview.Aspire.ResourceIsolation.SourceGeneration.Helpers;

static class PostInitExtensions
{
	/// <summary>
	/// Emits the <see cref="Microsoft.CodeAnalysis.EmbeddedAttribute"/> into the consuming
	/// compilation so that generated attributes can be marked as embedded without requiring
	/// the Roslyn analyzer package at runtime.
	/// </summary>
	public static void AddEmbeddedAttributeDefinition(this IncrementalGeneratorPostInitializationContext context)
	{
		context.AddSource(
			"EmbeddedAttribute.g.cs",
			@"// <auto-generated />
#nullable enable

#if !PURVIEW_ASPIRE_RESOURCE_ISOLATION_EMBEDDED_ATTRIBUTE

namespace Microsoft.CodeAnalysis
{
	[global::System.CodeDom.Compiler.GeneratedCode(""Purview.Aspire.ResourceIsolation.SourceGeneration"", ""1.0.0"")]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	sealed partial class EmbeddedAttribute : global::System.Attribute
	{
	}
}

#endif
"
		);
	}
}
