<Project>
	<Import Project="Versions.props" Condition="Exists('$(MSBuildThisFileDirectory)Versions.props')" />

	<PropertyGroup>
		<TargetFramework Condition="'$(TargetFrameworks)' == ''">$(DefaultTargetFramework)</TargetFramework>
		<NamespacePrefix>Purview.Aspire.ResourceKit</NamespacePrefix>
		<IsPackable>false</IsPackable>
		<RepositoryUrl>https://github.com/purview-dev/purview-aspire-resourcekit</RepositoryUrl>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup Label="NuGet package metadata">
		<Authors>Purview Contributors</Authors>
		<Company>Purview.dev</Company>
		<PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
		<RepositoryUrl>$(RepositoryUrl)</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageIcon>purview-logo.jpg</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None Include="$(MSBuildThisFileDirectory)/../LICENSE.md" Link="Sdk/LICENSE.md" />
		<None Include="$(MSBuildThisFileDirectory)/../assets/images/purview-logo.jpg" Link="Sdk/purview-logo.jpg" />
		<None Include="$(MSBuildThisFileDirectory)/../README.md" Link="Sdk/README.md" />
	</ItemGroup>
</Project>
