<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
	<ItemGroup>
		<ProjectReference Include="..\Example.Service\Example.Service.csproj" />
		<ProjectReference Include="..\ResourceKit\ResourceKit.csproj" IsAspireProjectResource="false" />
		<ProjectReference
			Include="..\SourceGeneration\SourceGeneration.csproj"
			IsAspireProjectResource="false"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
			PrivateAssets="all"
		/>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting" />
	</ItemGroup>
</Project>
