<Project>
	<ItemGroup Label="Compiler Visible SDK Properties">
		<CompilerVisibleProperty Include="DisableAspireResourceIsolationSourceGenerator">
			<Description>Specifies whether to disable Purview Aspire Resource Isolation source generators.</Description>
		</CompilerVisibleProperty>
	</ItemGroup>
</Project>
